baseURL = ""
title = "ÁcidoBase"
author = ""
copyright = "ÁcidoBase 2024"

timeZone = 'Europe/London'

# Multilingual
defaultContentLanguage = "pt"
defaultContentLanguageInSubdir = false

theme= "hugo-bootstrap-theme"
themesdir = 'node_modules/@filipecarneiro'


disableHugoGeneratorInject = true
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true
#sectionPagesMenu = "main"
googleAnalytics = "G-HQPH6MBHQ0"

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[taxonomies]
  tag = "tags"
  category = "categories"
  series = 'series'
  author = "authors"

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[permalinks]
#  post = "/post/:title/"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.99.1"
    max = ""
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"

[build]
  writeStats = true