# Site Params

# Open Graph, Twitter Cards and schema.org Thing and Article (in posts)
# https://gohugo.io/templates/internal/#open-graph
# https://gohugo.io/templates/internal/#twitter-cards
# https://schema.org/Thing
# https://schema.org/Article
description = "Associação Cultural"
images = ['images/logo_white.svg','images/logo.svg']
mainMenuLogo = "images/logo.svg"
altLogo = "images/logo_white.svg"

# For favicons
## Chrome Browser
themeColor = "#fff"

# Alert
alert = false
alertDismissable = true
alertText = "Introducing this new service! <a class=\"alert-link stretched-link\" href=\"https://salvus.site/\">Check out Total Security</a>"

# Pre-footer
footerAbout = true
footerAboutTitle = "ÁcidoBase"
footerAboutText = ""

[options]
  bootStrapJs = true
  breadCrumb = false
  listCategoryFilter = false
  listTagFilter = false

sticky_header = true

[organization]
  name = "ÁcidoBase"
  legalName = "ÁcidoBase Associação Cultural"
  url = "acidobase.org"
  address = {locality="Palmela", country = "Portugal"}

[webSite]
  name = "ÁcidoBase"
  copyrightHolder = {name = "ÁcidoBase"}
  url = "www.acidobase.org"