baseURL = 'https://acidobase.org/'
languageCode = 'pt-pt'
title = 'ÁcidoBase'
theme = 'ananke'

DefaultContentLanguage = "pt"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.pt]
    title = "ÁcidoBase"
    weight = 1
    contentDir = "content/pt"
    # languageDirection = 'rtl' for Right-To-Left languages

[params]
  text_color = ""
  author = "AcidoBase"
  favicon = ""  
  site_logo = ""
  description = "A Associação Cultural que faltava"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 2
  date_format = "2 de janeiro de 2006"
  #body_classes = "avenir bg-near-black"