baseURL = ""
languageCode = 'pt-pt'
title = 'ÁcidoBase'
theme= "hugo-bootstrap-theme"
themesdir = 'node_modules/@filipecarneiro'


homepage = "acidobase.org"

tags = ["acidobase", "palmela", "associacao cultural", "acido", "base"]
features = ["evento","musica","cidadania","ambiente"]