backend:
  name: github
  repo: inrx/acidobase
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://www.acidobase.org
  auth_endpoint: /api/auth
media_folder: "assets/images"
public_folder: /images
editor:
  preview: true
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog/"
    create: true
    path: "{{slug}}/index{{lang}}"
    media_library:
      folder_support: true
    media_folder: ""
    public_folder: ""
    extension: "md"
    summary: "[{{lang}}] {{title | upper}} - {{date | date('yyyy-MM-dd')}}"
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "Este título será apresentado na landing page.",
        }
      - {
          label: "Draft",
          name: "draft",
          widget: "boolean",
          hint: "Se pretendes que este artigo fique escondido.",
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          hint: "Se for no futuro, o artigo só será visível nessa data",
        }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
          hint: "Este texto é utilizado em todos os previews do artigo. Se não existir é utilizada uma parte do corpo do texto.",
        }
      - { label: "Body", name: "body", widget: "markdown", required: true }
      - { label: "Keywords", name: "keywords", widget: "list" }
      - {
          label: "Featured Images",
          name: "images",
          widget: "image",
          required: false,
        }
      - label: "Lang"
        name: "lang"
        widget: "select"
        options:
          - { label: "PT", value: "" }
          - { label: "EN", value: ".en" }
        required: true
