[[main]]
name = "A Ácido Base"
url = "about"
weight = 10
title = "Mais sobre a Associação"

#[[main]]
#identifier = "blog"
#name = "Notícias"
#url = "blog"
#weight = 40


[[social]]
  name = "Instagram"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-instagram'><use href='/images/feather/feather-sprite.svg#instagram'/></svg>"
  url = "https://www.instagram.com/acidobase.ac/"
  weight = 20
  title = "Segue-nos no Instagram"

[[social]]
  name = "Facebook"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-facebook'><use href='/images/feather/feather-sprite.svg#facebook'/></svg>"
  url = "https://www.facebook.com/acidobase.pH/"
  weight = 30
  title = "Segue-nos no Facebook"
