
[[main]]
name = "About Us"
url = "about"
weight = 20
title = "Know More"

[[main]]
name = "Tickets"
url = "https://acidobase.seetickets.com/"
weight = 20
title = "Buy Tickets"

[[social]]
  name = "Instagram"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-instagram'><use href='/images/feather/feather-sprite.svg#instagram'/></svg>"
  url = "https://www.instagram.com/acidobase.ac"
  weight = 20
  title = "Follow us on Instragram"

[[social]]
  name = "Facebook"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-facebook'><use href='/images/feather/feather-sprite.svg#facebook'/></svg>"
  url = "https://www.facebook.com/acidobase.pH"
  weight = 30
  title = "Follow us on Facebook"