[[main]]
name = "A Ácido Base"
url = "about"
weight = 10
title = "Mais sobre a Associação"

[[main]]
identifier = "tickets"
name = "Bilhetes"
url = "tickets"
weight = 20

#[[main]]
#identifier = "blog"
#name = "Notícias"
#url = "blog"
#weight = 40

#[[main]]
#name = "Todas as Notícias"
#url = "post"
#weight = 100
#parent = "blog"

#[[main]]
#name = "Cidadania"
#url = "tags/cidadania"
#weight = 20
#parent = "blog"
#
#[[main]]
#name = "Música"
#url = "tags/musica"
#weight = 30
#parent = "blog"

#[[main]]
#identifier = "docs"
#name = "Documentos"
#url = "page"
#weight = 50


[[social]]
  name = "Instagram"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-instagram'><use href='/images/feather/feather-sprite.svg#instagram'/></svg>"
  url = "https://www.instagram.com/acidobase.ac/"
  weight = 20
  title = "Segue-nos no Instagram"

[[social]]
  name = "Facebook"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-facebook'><use href='/images/feather/feather-sprite.svg#facebook'/></svg>"
  url = "https://www.facebook.com/acidobase.pH/"
  weight = 30
  title = "Segue-nos no Facebook"
