
[[main]]
name = "About Us"
url = "about"
weight = 20
title = "Know More"

[[main]]
identifier = "blog"
name = "News"
url = "blog"
weight = 40

#[[main]]
#name = "Todas as Notícias"
#url = "post"
#weight = 100
#parent = "blog"
#
#[[main]]
#name = "Events"
#url = "tags/events"
#weight = 20
#parent = "blog"
#
#[[main]]
#name = "Music"
#url = "tags/musica"
#weight = 30
#parent = "blog"

[[social]]
  name = "Instagram"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-instagram'><use href='/images/feather/feather-sprite.svg#instagram'/></svg>"
  url = "https://twitter.com/jfilipecarneiro/"
  weight = 20
  title = "See us on Instragram"
